### ISSUE TITLE
How to publish actual 'dist' Angular build not just the app

### ISSUE THREAD

**Issue by nathcoder** [GHCSCW/ProviderHub#50]
@alexpeasley can use for reference if its same as his app structure (i'm on RC6)

**Comment by alexpeasleyghc** [comment]
Just figured this out. Just out the C:\inetpub\wwwroot\SmallGroupRenewals2.0\ folder structure on WEBAPPD1. Then check out the IIS settings and web config file. It's using the URL rewrite inside IIS.
